services:
  db:
    image: postgres:16
    restart: always 
    volumes:
      - ./data/db:/var/lib/postgresql/data 
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  cache:
    image: redis:7.2.4
    restart: always
    volumes:
      - ./data/cache:/data
  notesapp:
    image: notesapp
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.prod
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_PORT=${EMAIL_PORT}
    volumes:
      - .:/notes
    depends_on:
      - db
      - cache
