[phases.setup]
nixPkgs = ['python311', 'postgresql', 'gcc']

[phases.install]
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt']

[phases.build]
cmds = ['python manage.py collectstatic --noinput']

[start]
cmd = 'gunicorn app.wsgi:application --bind 0.0.0.0:$PORT'
