[phases.setup]
nixPkgs = ['python311', 'postgresql', 'gcc']

[phases.install]
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt']

[phases.build]
cmds = ['DJANGO_SETTINGS_MODULE=app.settings.prod python manage.py collectstatic --noinput']

[start]
cmd = 'bash start.sh'

[variables]
DJANGO_SETTINGS_MODULE = "app.settings.prod"
PYTHONPATH = "/app"