# Generated by Django 5.1.1 on 2024-10-29 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_category_slug_tag_slug'),
        ('ideas', 'fix_empty_slugs'),
    ]

    operations = [
    ]
